[default]
timeout = 30

[npr-ukraine]
title = "NPR Ukraine Recap"
url = "https://www.npr.org/series/1084620843/russia-ukraine-recap"
entrySelector = "article"
titleSelector = "h2"
linkSelector = "h2 a"
contentSelector = ".teaser"
dateSelector = ".teaser time"
